export const CATEGORIES = [
    "actions",
    "adjectives",
    "animals",
    "anime",
    "art & design",
    "cartoons & comics",
    "celebrities",
    "decades",
    "emotions",
    "fashion & beauty",
    "food & drink",
    "gaming",
    "greetings",
    "holiday",
    "identity",
    "interests",
    "memes",
    "movies",
    "music",
    "nature",
    "news & politics",
    "reactions",
    "science",
    "sports",
    "stickers",
    "transportation",
    "tv",
    "weird"
    ]